Set default context at reading model from db
Set default context in from_db_value method and fix TypeError at opening model with ArrayReferenceField table in django admin
"""
from_db_value() missing 1 required positional argument: 'context'
"""